# setup services 
version: '3.8'

services:
  django:
    container_name: django
    build:
      context: .
    command: gunicorn ProjectFiles.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"  # Using port 16379 externally
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - app-network
    command: redis-server --appendonly yes

  celery:
    container_name: celery
    build:
      context: .
    command: celery -A ProjectFiles worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80" #http
      - "443:443" # https
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
      - ./certbot/www:/var/www/certbot #https
      - ./certbot/conf:/etc/letsencrypt #https
    depends_on:
      - django
    networks:
      - app-network
  certbot:
  image: certbot/certbot
  volumes:
    - ./certbot/www:/var/www/certbot
    - ./certbot/conf:/etc/letsencrypt 
    
networks:
  app-network:
    driver: bridge

